name: Build and Upload Penpot Bundles

on:
  # Create bundle from manual action
  workflow_dispatch:
  workflow_call:
    inputs:
      gh_ref:
        description: 'Name of the branch'
        type: string
        required: true

jobs:
  build-bundles:
    name: Build and Upload Penpot Bundles
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.gh_ref }}

      - name: Extract some useful variables
        id: vars
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "gh_ref=${{ inputs.gh_ref }}" >> $GITHUB_OUTPUT

      - name: Debug with tag
        if: github.ref_type == 'tag'
        run: |
          echo "tag: ${{ steps.vars.outputs.gh_ref}}"

      - name: Debug with branch
        if: github.ref_type == 'branch'
        run: |
          echo "branch: ${{ steps.vars.outputs.gh_ref}}"
