name: Build and Upload Penpot Bundles

on:
  # Create bundle from manual action
  workflow_dispatch:
  workflow_call:
    inputs:
      gh_ref:
        description: 'Name of the branch'
        type: string
        required: true

jobs:
  build-bundles:
    name: Build and Upload Penpot Bundles
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.gh_ref }}

      - name: Extract some useful variables
        id: vars
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "gh_branch=${{ inputs.gh_ref }}" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo ${{ steps.vars.outputs.gh_branch}}
